api/urls.py
from django.urls import path

from . import views

app_name = 'api'

urlpatterns = [
    path('discord/callback', views.discord_callback, name='discord_callback'),
]

genki/urls.py
"""genki URL Configuration"""
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from playthrough import views

urlpatterns = [
    path("", include("terminal.urls")),
    path("api/", include("api.urls", namespace="api")),
    path("admin/", admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns.append(path("__reload__/", include("django_browser_reload.urls")))
else:
    urlpatterns.append(
        path(
            "media/protected/<path:filename>", views.serve_archive, name="serve_archive"
        )
    )

terminal/urls.py
from django.urls import path

from . import views

app_name = 'terminal'

urlpatterns = [
    path('', views.index, name='index'),
    path('login', views.login, name='login'),
    path('logout', views.logout, name='logout'),
    path('archives', views.archives, name='archives'),
    path('archives/<int:archive_id>/delete', views.delete_archive, name='delete_archive'),
]

terminal/views.py
from urllib.parse import quote_plus
from django.db.models.query_utils import Q
from django.http.response import Http404, HttpResponse

from django.shortcuts import render, redirect
from django.conf import settings
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout as user_logout

from playthrough.models import Archive, Channel, User


def index(request):
    if request.user.is_authenticated:
        return redirect(reverse('terminal:archives'))
    return render(request, 'terminal/index.html')


def login(request):
    CLIENT_ID = settings.DISCORD_CLIENT_ID
    _redirect = quote_plus(request.build_absolute_uri(reverse('api:discord_callback')))

    return redirect((
        f'https://discord.com/api/oauth2/authorize?client_id={CLIENT_ID}&'
        f'redirect_uri={_redirect}&response_type=code&scope=identify'
    ))


def logout(request):
    user_logout(request)
    return redirect(reverse('terminal:index'))


@login_required(login_url='/login')
def archives(request):
    # TODO Move this to a custom wrapper function
    if request.user.__class__ != User:
        user_logout(request)
        return redirect(reverse('terminal:index'))
    _channels = Channel.objects.exclude(archives=None)\
        .select_related('game', 'game__series', 'guild')\
        .prefetch_related('archives').filter(
            Q(archives__users__in=[request.user]) | Q(owner=request.user)
        ).distinct()
    return render(request, 'terminal/archives.html', context={
        'channels': _channels
    })


@login_required(login_url='/login')
def delete_archive(request, archive_id):
    try:
        archive = Archive.objects.select_related('channel').get(pk=archive_id)
    except Archive.DoesNotExist:
        raise Http404("Archive does not exist.")
    if request.user.id != archive.channel.owner_id:
        return HttpResponse("Unauthorized", status=403)
    archive.delete()
    return redirect(reverse('terminal:archives'))

terminal/templates/terminal/archives.html
{% extends 'layout.html' %}
{% block content %}
    <div class="rounded-full absolute top-0 right-0 bg-white mx-3 my-3 p-3 font-mono">
        <a class="hover:text-blue-400" href="{% url 'terminal:logout' %}">Logout</a>
    </div>
    <div class="container mx-auto flex flex-col justify-center h-screen font-mono">
        <h1 class="text-blue-400 text-6xl pt-5 pb-3">Archives</h1>
        <div class="overflow-y-auto">
            {% if channels %}
                {% for channel in channels %}
                    <div class="w-fill rounded shadow-lg bg-white mb-4">
                        <div class="px-6 pt-4">
                            <div class="font-bold text-xl mb-2">
                                {{ channel.game.name }}
                                <span class="font-normal text-md text-gray-600">{{ channel.owner }}</span>
                            </div>
                            <ol class="divide-y divide-gray-400">
                                {% for archive in channel.archives.all %}
                                    <li class="py-1">
                                        <a class="hover:text-blue-400 hover:underline" href="{{ archive.file.url }}">Archive on {{ archive.created }}</a>
                                        {% if channel.owner == request.user %}
                                            <a class="float-right hover:text-red-400 text-gray-400 hover:underline" href="{% url 'terminal:delete_archive' archive.id %}">Delete</a>
                                        {% endif %}
                                    </li>
                                {% endfor %}
                            </ol>
                        </div>
                        <div class="px-6 pt-4 pb-2">
                            {% if channel.game.series %}
                                <span class="inline-block bg-gray-200 rounded-full px-3 py-1 text-sm font-semibold text-gray-700 mr-2 mb-2">{{ channel.game.series }}</span>
                            {% endif %}
                            {% if channel.finished %}
                                <span class="inline-block bg-green-200 rounded-full px-3 py-1 text-sm font-semibold text-gray-700 mr-2 mb-2">Finished</span>
                            {% endif %}
                            {% if channel.owner == request.user %}
                                <span class="inline-block bg-yellow-300 rounded-full px-3 py-1 text-sm font-semibold text-gray-700 mr-2 mb-2">Your channel</span>
                            {% endif %}
                        </div>
                    </div>
                {% endfor %}
            {% else %}
                <div class="w-fill rounded shadow-lg bg-white mb-4 p-4">
                    <p class="text-xl text-gray-700">You don't have any channel archives to view.</p>
                </div>
            {% endif %}
        </div>
    </div>
{% endblock %}

terminal/templates/terminal/index.html
{% extends 'layout.html' %}
{% block content %}
    <div class="container mx-auto flex flex-col justify-center h-screen">
        <div class="w-fill rounded-full p-3 overflow-hidden shadow-lg bg-white">
            <p class="font-mono text-6xl text-center">
                <a class="underline hover:text-blue-400" href="{% url 'terminal:login' %}">Log in</a> with Discord.
            </p>
        </div>
    </div>
{% endblock %}